#import "record.typ": impl_record, record
#import "enum.typ": enum, impl_enum
#import "meta.typ": _core_doc
#import "uid.typ": namespaces, v3
#import "state.typ": _mkstate

#let _ns_stlye = v3(namespaces.oid, "4cff74bd-1751-4de9-b29c-aa177649d4e9")
#let _style_uuid(name) = v3(_ns_stlye, name)

#let style = _mkstate(
  "123389fe-512d-499e-a357-a9bad0ca1926",
  (:),
)

page(
background: content | none,
binding: alignment | auto,
body: content,
columns: int,
fill: color,
flipped: bool,
footer: auto | content | none,
footer-descent: relative,
foreground: content | none,
header: auto | content | none,
header-ascent: relative,
margin: margin,
number-align: alignment,
numbering: function | none | str,
supplement: auto | content | none,
)

#let page_size = {
  let page_size = enum(
    a0: record(),
    a1: record(),
    a10: record(),
    a11: record(),
    a2: record(),
    a3: record(),
    a4: record(),
    a5: record(),
    a6: record(),
    a7: record(),
    a8: record(),
    a9: record(),
    ansi-a: record(),
    ansi-b: record(),
    ansi-c: record(),
    ansi-d: record(),
    ansi-e: record(),
    arch-a: record(),
    arch-b: record(),
    arch-c: record(),
    arch-d: record(),
    arch-e: record(),
    arch-e1: record(),
    asia-f4: record(),
    cn-business-card: record(),
    din-d3: record(),
    din-d4: record(),
    din-d5: record(),
    din-d6: record(),
    din-d7: record(),
    din-d8: record(),
    eu-business-card: record(),
    fr-carré: record(),
    fr-couronne-écriture: record(),
    fr-couronne-édition: record(),
    fr-jésus: record(),
    fr-raisin: record(),
    fr-tellière: record(),
    iso-b1: record(),
    iso-b2: record(),
    iso-b3: record(),
    iso-b4: record(),
    iso-b5: record(),
    iso-b6: record(),
    iso-b7: record(),
    iso-b8: record(),
    iso-c3: record(),
    iso-c4: record(),
    iso-c5: record(),
    iso-c6: record(),
    iso-c7: record(),
    iso-c8: record(),
    iso-id-1: record(),
    iso-id-2: record(),
    iso-id-3: record(),
    jis-b0: record(),
    jis-b1: record(),
    jis-b10: record(),
    jis-b11: record(),
    jis-b2: record(),
    jis-b3: record(),
    jis-b4: record(),
    jis-b5: record(),
    jis-b6: record(),
    jis-b7: record(),
    jis-b8: record(),
    jis-b9: record(),
    jp-business-card: record(),
    jp-kiku-4: record(),
    jp-kiku-5: record(),
    jp-shiroku-ban-4: record(),
    jp-shiroku-ban-5: record(),
    jp-shiroku-ban-6: record(),
    newspaper-berliner: record(),
    newspaper-broadsheet: record(),
    newspaper-compact: record(),
    presentation-16-9: record(),
    presentation-4-3: record(),
    sac-d0: record(),
    sac-d1: record(),
    sac-d2: record(),
    sac-d3: record(),
    sac-d4: record(),
    sac-d5: record(),
    sac-d6: record(),
    sis-e5: record(),
    sis-g5: record(),
    uk-book-a: record(),
    uk-book-b: record(),
    uk-brief: record(),
    uk-crown: record(),
    uk-draft: record(),
    uk-foolscap: record(),
    uk-quarto: record(),
    us-business-card: record(),
    us-digest: record(),
    us-executive: record(),
    us-foolscap-folio: record(),
    us-gov-legal: record(),
    us-gov-letter: record(),
    us-ledger: record(),
    us-legal: record(),
    us-letter: record(),
    us-oficio: record(),
    us-statement: record(),
    us-tabloid: record(),
    us-trade: record(),
    custom: record(
      width: length,
      height: length,
    ),
  )

  page_size = impl_enum(
    page_size,
    display: self => {
      it => {
        if "custom" == self.variant {
          show page: set page(width: self.payload.width, height: self.payload.height)
        } else {
          show page: set page(paper: self.variant)
        }
      }
    },
  )

  page_size = (
    page_size
      + (
        a0: (page_size.a0)(),
        a1: (page_size.a1)(),
        a10: (page_size.a10)(),
        a11: (page_size.a11)(),
        a2: (page_size.a2)(),
        a3: (page_size.a3)(),
        a4: (page_size.a4)(),
        a5: (page_size.a5)(),
        a6: (page_size.a6)(),
        a7: (page_size.a7)(),
        a8: (page_size.a8)(),
        a9: (page_size.a9)(),
        ansi-a: (page_size.ansi-a)(),
        ansi-b: (page_size.ansi-b)(),
        ansi-c: (page_size.ansi-c)(),
        ansi-d: (page_size.ansi-d)(),
        ansi-e: (page_size.ansi-e)(),
        arch-a: (page_size.arch-a)(),
        arch-b: (page_size.arch-b)(),
        arch-c: (page_size.arch-c)(),
        arch-d: (page_size.arch-d)(),
        arch-e: (page_size.arch-e)(),
        arch-e1: (page_size.arch-e1)(),
        asia-f4: (page_size.asia-f4)(),
        cn-business-card: (page_size.cn-business-card)(),
        din-d3: (page_size.din-d3)(),
        din-d4: (page_size.din-d4)(),
        din-d5: (page_size.din-d5)(),
        din-d6: (page_size.din-d6)(),
        din-d7: (page_size.din-d7)(),
        din-d8: (page_size.din-d8)(),
        eu-business-card: (page_size.eu-business-card)(),
        fr-carré: (page_size.fr-carré)(),
        fr-couronne-écriture: (page_size.fr-couronne-écriture)(),
        fr-couronne-édition: (page_size.fr-couronne-édition)(),
        fr-jésus: (page_size.fr-jésus)(),
        fr-raisin: (page_size.fr-raisin)(),
        fr-tellière: (page_size.fr-tellière)(),
        iso-b1: (page_size.iso-b1)(),
        iso-b2: (page_size.iso-b2)(),
        iso-b3: (page_size.iso-b3)(),
        iso-b4: (page_size.iso-b4)(),
        iso-b5: (page_size.iso-b5)(),
        iso-b6: (page_size.iso-b6)(),
        iso-b7: (page_size.iso-b7)(),
        iso-b8: (page_size.iso-b8)(),
        iso-c3: (page_size.iso-c3)(),
        iso-c4: (page_size.iso-c4)(),
        iso-c5: (page_size.iso-c5)(),
        iso-c6: (page_size.iso-c6)(),
        iso-c7: (page_size.iso-c7)(),
        iso-c8: (page_size.iso-c8)(),
        iso-id-1: (page_size.iso-id-1)(),
        iso-id-2: (page_size.iso-id-2)(),
        iso-id-3: (page_size.iso-id-3)(),
        jis-b0: (page_size.jis-b0)(),
        jis-b1: (page_size.jis-b1)(),
        jis-b10: (page_size.jis-b10)(),
        jis-b11: (page_size.jis-b11)(),
        jis-b2: (page_size.jis-b2)(),
        jis-b3: (page_size.jis-b3)(),
        jis-b4: (page_size.jis-b4)(),
        jis-b5: (page_size.jis-b5)(),
        jis-b6: (page_size.jis-b6)(),
        jis-b7: (page_size.jis-b7)(),
        jis-b8: (page_size.jis-b8)(),
        jis-b9: (page_size.jis-b9)(),
        jp-business-card: (page_size.jp-business-card)(),
        jp-kiku-4: (page_size.jp-kiku-4)(),
        jp-kiku-5: (page_size.jp-kiku-5)(),
        jp-shiroku-ban-4: (page_size.jp-shiroku-ban-4)(),
        jp-shiroku-ban-5: (page_size.jp-shiroku-ban-5)(),
        jp-shiroku-ban-6: (page_size.jp-shiroku-ban-6)(),
        newspaper-berliner: (page_size.newspaper-berliner)(),
        newspaper-broadsheet: (page_size.newspaper-broadsheet)(),
        newspaper-compact: (page_size.newspaper-compact)(),
        presentation-16-9: (page_size.presentation-16-9)(),
        presentation-4-3: (page_size.presentation-4-3)(),
        sac-d0: (page_size.sac-d0)(),
        sac-d1: (page_size.sac-d1)(),
        sac-d2: (page_size.sac-d2)(),
        sac-d3: (page_size.sac-d3)(),
        sac-d4: (page_size.sac-d4)(),
        sac-d5: (page_size.sac-d5)(),
        sac-d6: (page_size.sac-d6)(),
        sis-e5: (page_size.sis-e5)(),
        sis-g5: (page_size.sis-g5)(),
        uk-book-a: (page_size.uk-book-a)(),
        uk-book-b: (page_size.uk-book-b)(),
        uk-brief: (page_size.uk-brief)(),
        uk-crown: (page_size.uk-crown)(),
        uk-draft: (page_size.uk-draft)(),
        uk-foolscap: (page_size.uk-foolscap)(),
        uk-quarto: (page_size.uk-quarto)(),
        us-business-card: (page_size.us-business-card)(),
        us-digest: (page_size.us-digest)(),
        us-executive: (page_size.us-executive)(),
        us-foolscap-folio: (page_size.us-foolscap-folio)(),
        us-gov-legal: (page_size.us-gov-legal)(),
        us-gov-letter: (page_size.us-gov-letter)(),
        us-ledger: (page_size.us-ledger)(),
        us-legal: (page_size.us-legal)(),
        us-letter: (page_size.us-letter)(),
        us-oficio: (page_size.us-oficio)(),
        us-statement: (page_size.us-statement)(),
        us-tabloid: (page_size.us-tabloid)(),
        us-trade: (page_size.us-trade)(),
        cn-is-degree-full: (page_size.custom)(width: 787mm, height: 1092mm),
        cn-magnanimous-full: (page_size.custom)(width: 889mm, height: 1194mm),
      )
  )

  page_size
}
